Develop feature bestellung + Lager + Einkauf
Shaco74/SWE-MehrMarkt pull request #26
Opened 2022-12-09 11:57 UTC by majdbousaad

Bestellung: Man kann jetzt in den Warenkorb Hinzufügen und schließlich bestellen

Einkauf: fetching Anstehende + Ausstehende Lieferungen + ein IconButton "zugestellt" als Post request

Lager: getching Lager products

2022-12-09 17:05 UTC, Shaco74 requested changes
Good Job! Bitte schau dir noch meine Anmerkungen an. :)

2022-12-09 17:05 UTC, Shaco74 commented on Frontend/src/pages/Einkauf/EinkaufPage.tsx
> +import OpenInNew from 'mdi-material-ui/OpenInNew'
Das hier ist der richtige import. Icons werden hier von `'mdi-material-ui/OpenInNew'` importiert, da das die icons sind welche vom Template angepasst wurden.  Bitte tausche alle `'@mui/icons-material/*'` durch die richtigen aus. @majdbousaad

2022-12-09 17:05 UTC, Shaco74 commented on Frontend/src/pages/Einkauf/EinkaufPage.tsx
> +import { Box, CardHeader, IconButton, Table, TableBody, TableCell, TableHead, TableRow } from '@mui/material'
Das hier führt zwar zu keinem Error aber grundsätzlich finde ich das bad practise da das zu längeren Compiletimes im development führt. Besser ist es alles explizit zu importen wie in den ersten 3 Zeilen. @majdbousaad

2022-12-09 17:05 UTC, Shaco74 commented on Frontend/package.json
> +    "@mui/icons-material": "^5.10.16",
Dieser Import wird nicht gebraucht. @majdbousaad

2022-12-09 17:05 UTC, Shaco74 commented on Frontend/src/pages/Einkauf/EinkaufPage.tsx
> +  function fetchAnstehendeLiefererungen(): void {
Sehr gut dass du jetzt auch axios nutzt 😉 👍 . Gut dass du auch dummy catch blocks eingebaut hast, damit wir keine crashes kriegen in der demo

2022-12-09 17:05 UTC, Shaco74 commented on Frontend/src/views/dashboard/TodaysSells.tsx
> +          {anzahl.anzahl}
Nicht unbedingt most readable code aber lass ich gelten für SWE 🤣

2022-12-09 22:07 UTC, majdbousaad commented on Frontend/src/views/dashboard/TodaysSells.tsx
> +          {anzahl.anzahl}
HAHAHAHA

2022-12-09 22:09 UTC, majdbousaad commented on Frontend/src/pages/Einkauf/EinkaufPage.tsx
> +import { Box, CardHeader, IconButton, Table, TableBody, TableCell, TableHead, TableRow } from '@mui/material'
Ja vollkommen richtig, Ich dachte nie an Optimieren

2022-12-09 22:15 UTC, majdbousaad commented on Frontend/src/pages/Einkauf/EinkaufPage.tsx
> +import OpenInNew from 'mdi-material-ui/OpenInNew'
Kannst du mehr darüber erzählen? Die funktionieren schon ohne Build Errors.

2022-12-12 12:00 UTC, Shaco74 commented
@majdbousaad hey sieht doch schon mal besser aus, sehr nice!
Ich finde den Ansatz mit dem Alert "Es gibt keine Verbindung zu Datenbank" eine sehr gute Idee, leider lässt dieser sich nicht schließen. Könntest du das noch abschließend fixen dass man auch im offline mode mindestens die UI geladen bekommt auch ohne backend? Der Alert öffnet sich bei mir immer wieder. 
Dannach können wir gerne mergen 👍 GJ!

2022-12-12 19:26 UTC, merged